
# Dictionary with the info related to a Ticket Transaction. 

mix_transaction = {

    "M001" : "Purge Current Mix File",
    "M002" : "Begin Mix",
    "M003" : "End Mix",
    "M007" : "Mix Data Field",
    "M017" : "Success Reply",
    "M021" : "Failure Reply",
    "001" : "Mix Code(BatchBook ID)",
    "002" : "Mix Description",
    "003" : "Agg #1 Product Name",
    "004" : "Agg #1 Weight (lb/kg)",
    "005" : "Agg #2 Product Name",
    "006" : "Agg #2 Weight (lb/kg)",
    "007" : "Agg #3 Product Name",
    "008" : "Agg #3 Weight (lb/kg)",
    "009" : "Agg #4 Product Name",
    "010" : "Agg #4 Weight (lb/kg)",
    "011" : "Cement #1 Product Name",
    "012" : "Cement #1 Weight (lb/kg)",
    "013" : "Cement #2 Product Name",
    "014" : "Cement #2 Weight (lb/kg)",
    "015" : "Water #1 Product Name",
    "016" : "Water #1 Weighed Units/ Metered Units",
    "017" : "Admix #1 Product Name", 
    "018" : "Admix #1 Unit (oz/mL)",
    "019" : "Admix #2 Product Name", 
    "020" : "Admix #2 Unit (oz/mL)",
    "021" : "Admix #3 Product Name", 
    "022" : "Admix #3 Unit (oz/mL)",
    "023" : "Admix #4 Product Name", 
    "024" : "Admix #4 Unit (oz/mL)",
    "025" : "Admix #5 Product Name", 
    "026" : "Admix #5 Unit (oz/mL)",
    "027" : "Admix #6 Product Name", 
    "028" : "Admix #6 Unit (oz/mL)",
    "029" : "Cement #3 Product Name",
    "030" : "Cement #3 Weight (lb/kg)",
    "031" : "Water #2 Product Name",
    "032" : "Water #2 Weighed Units/ Metered Units",
    "033" : "Mixer Time",
    "034" : "Maximum Load Size",
    "035" : "Agg #5 Product Name",
    "036" : "Agg #5 Weight (lb/kg)",
    "037" : "Percent Air",
    "038" : "Slump Target",
    "039" : "Maximum Dry load Size",
    "040" : "Maximum Async Load Size",
    "041" : "Agg Moisture Reference",
    "042" : "Metric (Y/N)",
    "043" : "Consistence",
    "044" : "Extended Description",
    "045" : "RESERVED",
    "046" : "Maximum Water Cement Ratio",


}